# Generated by Django 3.0.7 on 2020-06-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='shoppingcart.CartItem'),
        ),
    ]
